/*******************************************************************************
* File Name: PM.c
* Version 2.60
*
* Description:
*  This file provides the source code to the API for the Sequencing Successive
*  Approximation ADC Component Component.
*
* Note:
*
********************************************************************************
* Copyright 2008-2017, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "PM.h"


/***************************************
* Global data allocation
***************************************/
uint8 PM_initVar = 0u;
volatile int16 PM_offset[PM_TOTAL_CHANNELS_NUM];
volatile int32 PM_countsPer10Volt[PM_TOTAL_CHANNELS_NUM];   /* Gain compensation */


/***************************************
* Local data allocation
***************************************/
/* Channels configuration generated by customiser */
static const uint32 CYCODE PM_channelsConfig[] = { 0x00000000u };


/*******************************************************************************
* Function Name: PM_Start
********************************************************************************
*
* Summary:
*  Performs all required initialization for this component
*  and enables the power. The power will be set to the appropriate
*  power based on the clock frequency.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
* Global variables:
*  The PM_initVar variable is used to indicate when/if initial
*  configuration of this component has happened. The variable is initialized to
*  zero and set to 1 the first time ADC_Start() is called. This allows for
*  component Re-Start without re-initialization in all subsequent calls to the
*  PM_Start() routine.
*  If re-initialization of the component is required the variable should be set
*  to zero before call of PM_Start() routine, or the user may call
*  PM_Init() and PM_Enable() as done in the
*  PM_Start() routine.
*
*******************************************************************************/
void PM_Start(void)
{
    /* If not Initialized then initialize all required hardware and software */
    if(PM_initVar == 0u)
    {
        PM_Init();
        PM_initVar = 1u;
    }
    PM_Enable();
}


/*******************************************************************************
* Function Name: PM_Init
********************************************************************************
*
* Summary:
*  Initialize component's parameters to the parameters set by user in the
*  customizer of the component placed onto schematic. Usually called in
*  PM_Start().
*
* Parameters:
*  None.
*
* Return:
*  None.
*
* Global variables:
*  The PM_offset variable is initialized.
*
*******************************************************************************/
void PM_Init(void)
{
    uint32 chNum;
    uint32 tmpRegVal;
    int32 counts;

    #if(PM_TOTAL_CHANNELS_NUM > 1u)
        static const uint8 CYCODE PM_InputsPlacement[] =
        {
            (uint8)(PM_cy_psoc4_sarmux_8__CH_0_PORT << 4u) |
            (uint8)PM_cy_psoc4_sarmux_8__CH_0_PIN
            ,(uint8)(PM_cy_psoc4_sarmux_8__CH_1_PORT << 4u) |
             (uint8)PM_cy_psoc4_sarmux_8__CH_1_PIN
            #if(PM_TOTAL_CHANNELS_NUM > 2u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_2_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_2_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 2u */
            #if(PM_TOTAL_CHANNELS_NUM > 3u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_3_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_3_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 3u */
            #if(PM_TOTAL_CHANNELS_NUM > 4u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_4_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_4_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 4u */
            #if(PM_TOTAL_CHANNELS_NUM > 5u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_5_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_5_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 5u */
            #if(PM_TOTAL_CHANNELS_NUM > 6u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_6_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_6_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 6u */
            #if(PM_TOTAL_CHANNELS_NUM > 7u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_7_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_7_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 7u */
            #if(PM_TOTAL_CHANNELS_NUM > 8u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_8_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_8_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 8u */
            #if(PM_TOTAL_CHANNELS_NUM > 9u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_9_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_9_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 9u */
            #if(PM_TOTAL_CHANNELS_NUM > 10u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_10_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_10_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 10u */
            #if(PM_TOTAL_CHANNELS_NUM > 11u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_11_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_11_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 11u */
            #if(PM_TOTAL_CHANNELS_NUM > 12u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_12_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_12_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 12u */
            #if(PM_TOTAL_CHANNELS_NUM > 13u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_13_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_13_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 13u */
            #if(PM_TOTAL_CHANNELS_NUM > 14u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_14_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_14_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 14u */
            #if(PM_TOTAL_CHANNELS_NUM > 15u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_15_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_15_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 15u */
            #if(PM_TOTAL_CHANNELS_NUM > 16u)
                ,(uint8)(PM_cy_psoc4_sarmux_8__CH_16_PORT << 4u) |
                 (uint8)PM_cy_psoc4_sarmux_8__CH_16_PIN
            #endif /* End PM_TOTAL_CHANNELS_NUM > 16u */
        };
    #endif /* End PM_TOTAL_CHANNELS_NUM > 1u */

    #if(PM_IRQ_REMOVE == 0u)
        /* Start and set interrupt vector */
        CyIntSetPriority(PM_INTC_NUMBER, PM_INTC_PRIOR_NUMBER);
        (void)CyIntSetVector(PM_INTC_NUMBER, &PM_ISR);
    #endif   /* End PM_IRQ_REMOVE */

    /* Init SAR and MUX registers */
    PM_SAR_CHAN_EN_REG = PM_DEFAULT_EN_CHANNELS;
    PM_SAR_CTRL_REG |= PM_DEFAULT_CTRL_REG_CFG | 
        /* Enable the SAR internal pump when global pump is enabled */
        (((PM_PUMP_CTRL_REG & PM_PUMP_CTRL_ENABLED) != 0u) ? 
        PM_BOOSTPUMP_EN : 0u);
    PM_SAR_SAMPLE_CTRL_REG = PM_DEFAULT_SAMPLE_CTRL_REG_CFG;
    PM_SAR_RANGE_THRES_REG = PM_DEFAULT_RANGE_THRES_REG_CFG;
    PM_SAR_RANGE_COND_REG  = PM_COMPARE_MODE;
    PM_SAR_SAMPLE_TIME01_REG = PM_DEFAULT_SAMPLE_TIME01_REG_CFG;
    PM_SAR_SAMPLE_TIME23_REG = PM_DEFAULT_SAMPLE_TIME23_REG_CFG;
    
    /* Connect Vm to VSSA when even one channel is single-ended or multiple channels configured */
    #if(PM_DEFAULT_MUX_SWITCH0 != 0u)
        PM_MUX_SWITCH0_REG |= PM_DEFAULT_MUX_SWITCH0;
        /* Set MUX_HW_CTRL_VSSA in MUX_SWITCH_HW_CTRL when multiple channels enabled */
        #if(PM_TOTAL_CHANNELS_NUM > 1u)
            PM_MUX_SWITCH_HW_CTRL_REG |= PM_DEFAULT_MUX_SWITCH0;
        #endif /* PM_TOTAL_CHANNELS_NUM > 1u */
    #endif /*PM_CHANNELS_MODE !=0 */

    PM_SAR_SATURATE_INTR_MASK_REG = 0u;
    PM_SAR_RANGE_INTR_MASK_REG = 0u;
    PM_SAR_INTR_MASK_REG = PM_SAR_INTR_MASK;

    #if(PM_CY_SAR_IP_VER == PM_CY_SAR_IP_VER0)
        PM_ANA_TRIM_REG = PM_TRIM_COEF;
    #endif /* (PM_CY_SAR_IP_VER == PM_CY_SAR_IP_VER0) */

    /* Read and modify default configuration based on characterization */
    tmpRegVal = PM_SAR_DFT_CTRL_REG;
    tmpRegVal &= (uint32)~PM_DCEN;
    
    #if(PM_CY_SAR_IP_VER == PM_CY_SAR_IP_VER0)
        #if(PM_NOMINAL_CLOCK_FREQ > (PM_MAX_FREQUENCY / 2))
            tmpRegVal |= PM_SEL_CSEL_DFT_CHAR;
        #else  /* clock speed < 9 Mhz */
            tmpRegVal |= PM_DLY_INC;
        #endif /* clock speed > 9 Mhz */
    #else
        #if ((PM_DEFAULT_VREF_SEL == PM__INTERNAL1024) || \
             (PM_DEFAULT_VREF_SEL == PM__INTERNALVREF))
            tmpRegVal |= PM_DLY_INC;
        #else
            tmpRegVal |= PM_DCEN;
            tmpRegVal &= (uint32)~PM_DLY_INC;
        #endif /* ((PM_DEFAULT_VREF_SEL == PM__INTERNAL1024) || \
                   (PM_DEFAULT_VREF_SEL == PM__INTERNALVREF)) */
    #endif /* (PM_CY_SAR_IP_VER == PM_CY_SAR_IP_VER0) */
    
    PM_SAR_DFT_CTRL_REG = tmpRegVal;

    #if(PM_MAX_RESOLUTION != PM_RESOLUTION_12)
        PM_WOUNDING_REG = PM_ALT_WOUNDING;
    #endif /* PM_MAX_RESOLUTION != PM_RESOLUTION_12 */

    for(chNum = 0u; chNum < PM_TOTAL_CHANNELS_NUM; chNum++)
    {
        tmpRegVal = (PM_channelsConfig[chNum] & PM_CHANNEL_CONFIG_MASK);
        #if(PM_TOTAL_CHANNELS_NUM > 1u)
            tmpRegVal |= PM_InputsPlacement[chNum];
        #endif /* End PM_TOTAL_CHANNELS_NUM > 1u */
        
        
        /* When the part is limited to 10-bit then the SUB_RESOLUTION bit
        *  will be ignored and the RESOLUTION bit selects between 10-bit
        *  (0) and 8-bit (1) resolution.
        */
        #if((PM_MAX_RESOLUTION != PM_RESOLUTION_12) && \
            (PM_ALT_WOUNDING == PM_WOUNDING_10BIT))
            tmpRegVal &= (uint32)(~PM_ALT_RESOLUTION_ON);
        #endif /* PM_MAX_RESOLUTION != PM_RESOLUTION_12 */

        #if(PM_INJ_CHANNEL_ENABLED)
        if(chNum < PM_SEQUENCED_CHANNELS_NUM)
        #endif /* PM_INJ_CHANNEL_ENABLED */
        {
            CY_SET_REG32((reg32 *)(PM_SAR_CHAN_CONFIG_IND + (uint32)(chNum << 2)), tmpRegVal);

            if((PM_channelsConfig[chNum] & PM_IS_SATURATE_EN_MASK) != 0u)
            {
                PM_SAR_SATURATE_INTR_MASK_REG |= (uint16)((uint16)1 << chNum);
            }

            if((PM_channelsConfig[chNum] & PM_IS_RANGE_CTRL_EN_MASK) != 0u)
            {
                PM_SAR_RANGE_INTR_MASK_REG |= (uint16)((uint16)1 << chNum);
            }
        }
        #if(PM_INJ_CHANNEL_ENABLED)
            else
            {
                CY_SET_REG32(PM_SAR_INJ_CHAN_CONFIG_PTR, tmpRegVal | PM_INJ_TAILGATING);

                if((PM_channelsConfig[chNum] & PM_IS_SATURATE_EN_MASK) != 0u)
                {
                    PM_SAR_INTR_MASK_REG |= PM_INJ_SATURATE_MASK;
                }

                if((PM_channelsConfig[chNum] & PM_IS_RANGE_CTRL_EN_MASK) != 0u)
                {
                    PM_SAR_INTR_MASK_REG |= PM_INJ_RANGE_MASK;
                }
            }
        #endif /* PM_INJ_CHANNEL_ENABLED */

        if((PM_channelsConfig[chNum] & PM_ALT_RESOLUTION_ON) != 0u)
        {
               counts = (int32)PM_DEFAULT_MAX_WRK_ALT;
        }
        else
        {
               counts = (int32)PM_SAR_WRK_MAX_12BIT;
        }

        if((PM_channelsConfig[chNum] & PM_DIFFERENTIAL_EN) == 0u)
        {
            #if((PM_DEFAULT_SE_RESULT_FORMAT_SEL == PM__FSIGNED) && \
                (PM_DEFAULT_NEG_INPUT_SEL == PM__VREF))
                /* Set offset to the minus half scale to convert results to unsigned format */
                PM_offset[chNum] = (int16)(counts / -2);
            #else
                PM_offset[chNum] = 0;
            #endif /* end DEFAULT_SE_RESULT_FORMAT_SEL == PM__FSIGNED */
        }
        else    /* Differential channel */
        {
            #if(PM_DEFAULT_DIFF_RESULT_FORMAT_SEL == PM__FUNSIGNED)
                /* Set offset to the half scale to convert results to signed format */
                PM_offset[chNum] = (int16)(counts / 2);
            #else
                PM_offset[chNum] = 0;
            #endif /* end PM_DEFAULT_DIFF_RESULT_FORMAT_SEL == PM__FUNSIGNED */
        }
        /* Calculate gain in counts per 10 volts with rounding */
        PM_countsPer10Volt[chNum] = (int16)(((counts * PM_10MV_COUNTS) +
                            PM_DEFAULT_VREF_MV_VALUE) / (PM_DEFAULT_VREF_MV_VALUE * 2));
    }
}

/*******************************************************************************
* Function Name: ADC_SAR_1_Enable
********************************************************************************
*
* Summary:
*  Enables the clock and analog power for SAR ADC.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void PM_Enable(void)
{
    if (0u == (PM_SAR_CTRL_REG & PM_ENABLE))
    {
        #if(PM_CY_SAR_IP_VER != PM_CY_SAR_IP_VER0)

            while (0u != (PM_SAR_STATUS_REG & PM_STATUS_BUSY))
            {
                /* wait for SAR to go idle to avoid deadlock */
            }
        #endif /* (PM_CY_SAR_IP_VER != PM_CY_SAR_IP_VER0) */
        
        PM_SAR_CTRL_REG |= PM_ENABLE;
        
        /* The block is ready to use 10 us after the enable signal is set high. */
        CyDelayUs(PM_10US_DELAY);         
    }
}


/*******************************************************************************
* Function Name: PM_Stop
********************************************************************************
*
* Summary:
*  This function stops ADC conversions and puts the ADC into its lowest power
*  mode.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void PM_Stop(void)
{
    PM_SAR_CTRL_REG &= (uint32)~PM_ENABLE;
}


/*******************************************************************************
* Function Name: PM_StartConvert
********************************************************************************
*
* Summary:
*  Description:
*  For free running mode, this API starts the conversion process and it
*  runs continuously.
*
*  In a triggered mode, this routine triggers every conversion by
*  writing into the FW_TRIGGER bit in SAR_START_CTRL reg. In triggered mode,
*  every conversion has to start by this API.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void PM_StartConvert(void)
{
    #if(PM_DEFAULT_SAMPLE_MODE_SEL == PM__FREERUNNING)
        PM_SAR_SAMPLE_CTRL_REG |= PM_CONTINUOUS_EN;
    #else /* Firmware trigger */
        PM_SAR_START_CTRL_REG = PM_FW_TRIGGER;
    #endif /* End PM_DEFAULT_SAMPLE_MODE == PM__FREERUNNING */

}


/*******************************************************************************
* Function Name: PM_StopConvert
********************************************************************************
*
* Summary:
*  Forces the ADC to stop all conversions.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void PM_StopConvert(void)
{
    #if(PM_DEFAULT_SAMPLE_MODE_SEL == PM__FREERUNNING)
        PM_SAR_SAMPLE_CTRL_REG &= (uint32)(~PM_CONTINUOUS_EN);
    #endif /* PM_DEFAULT_SAMPLE_MODE == PM__FREERUNNING */
}


/*******************************************************************************
* Function Name: PM_IsEndConversion
********************************************************************************
*
* Summary:
*  Description: Checks for ADC end of conversion for the case one
*  channel and end of scan for the case of multiple channels. It acts
*  as a software version of the EOC. This function provides the
*  programmer with two options. In one mode this function
*  immediately returns with the conversion status. In the other mode,
*  the function does not return (blocking) until the conversion has
*  completed.
*
* Parameters:
*  ADC_RETURN_STATUS        -> Immediately returns conversion result status
*  ADC_WAIT_FOR_RESULT      -> Does not return until ADC complete
*  ADC_RETURN_STATUS_INJ    -> Immediately returns conversion result status
*                              for injection channel
*  ADC_WAIT_FOR_RESULT_INJ  -> Does not return until ADC completes injection
*                              channel conversion
*
* Return:
*  If a non-zero value is returned, the last conversion or scan has completed.
*  If the returned value is zero, the ADC is still in the process of a scan.
*
*******************************************************************************/
uint32 PM_IsEndConversion(uint32 retMode)
{
    uint32 status = 0u;

    if((retMode & (PM_RETURN_STATUS | PM_WAIT_FOR_RESULT)) != 0u)
    {
        do
        {
            status = PM_SAR_INTR_REG & PM_EOS_MASK;
        }while((status == 0u) && ((retMode & PM_WAIT_FOR_RESULT) != 0u));

        if(status != 0u)
        {
            /* Clear EOS bit */
            PM_SAR_INTR_REG = PM_EOS_MASK;
        }
    }

    #if(PM_INJ_CHANNEL_ENABLED)
        if((retMode & (PM_RETURN_STATUS_INJ | PM_WAIT_FOR_RESULT_INJ)) != 0u)
        {
            do
            {
                status |= PM_SAR_INTR_REG & PM_INJ_EOC_MASK;
            }while(((status & PM_INJ_EOC_MASK) == 0u) &&
                   ((retMode & PM_WAIT_FOR_RESULT_INJ) != 0u));

            if((status & PM_INJ_EOC_MASK) != 0u)
            {
                /* Clear Injection EOS bit */
                PM_SAR_INTR_REG = PM_INJ_EOC_MASK;
            }
        }
    #endif /* PM_INJ_CHANNEL_ENABLED */

    return (status);
}


/*******************************************************************************
* Function Name: PM_GetResult16
********************************************************************************
*
* Summary:
*  Gets the data available in the SAR DATA register.
*
* Parameters:
*  chan: The ADC channel in which to return the result. The first channel
*  is 0 and the injection channel if enabled is the number of valid channels.
*
* Return:
*  Returns converted data as a signed 16-bit integer
*
*******************************************************************************/
int16 PM_GetResult16(uint32 chan)
{
    uint32 result;

    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < PM_TOTAL_CHANNELS_NUM);

    if(chan < PM_SEQUENCED_CHANNELS_NUM)
    {
        result = CY_GET_REG32((reg32 *)(PM_SAR_CHAN_RESULT_IND + (uint32)(chan << 2u))) &
                PM_RESULT_MASK;
    }
    else
    {
        #if(PM_INJ_CHANNEL_ENABLED)
            result = PM_SAR_INJ_RESULT_REG & PM_RESULT_MASK;
        #else
            result = 0u;
        #endif /* PM_INJ_CHANNEL_ENABLED */
    }

    return ( (int16)result );
}


/*******************************************************************************
* Function Name: PM_SetChanMask
********************************************************************************
*
* Summary:
*  Sets the channel enable mask.
*
* Parameters:
*  mask: Sets which channels that will be
*  scanned. Setting bits for channels that do not exist will have no
*  effect. For example, if only 6 channels were enabled, setting a
*  mask of 0x0103 would only enable the last two channels (0 and 1).
*  This API will not enable the injection channel.
*  Examples: If the component is setup to sequence through 8
*  channels, a mask of 0x000F would enable channels 0, 1, 2, and 3.
*
* Return:
*  None.
*
*******************************************************************************/
void PM_SetChanMask(uint32 mask)
{
    PM_SAR_CHAN_EN_REG = mask & PM_MAX_CHANNELS_EN_MASK;
}

#if(PM_INJ_CHANNEL_ENABLED)


    /*******************************************************************************
    * Function Name: PM_EnableInjection
    ********************************************************************************
    *
    * Summary:
    *  Enables the injection channel for the next scan only.
    *
    * Parameters:
    *  None.
    *
    * Return:
    *  None.
    *
    *******************************************************************************/
    void PM_EnableInjection(void)
    {
        PM_SAR_INJ_CHAN_CONFIG_REG |= PM_INJ_CHAN_EN;
    }

#endif /* PM_INJ_CHANNEL_ENABLED */


/*******************************************************************************
* Function Name: PM_SetLowLimit
********************************************************************************
*
* Summary:
*  Sets the low limit parameter for a limit condition.
*
* Parameters:
*  lowLimit: The low limit for a limit condition.
*
* Return:
*  None.
*
*******************************************************************************/
void PM_SetLowLimit(uint32 lowLimit)
{
    PM_SAR_RANGE_THRES_REG &= (uint32)(~PM_RANGE_LOW_MASK);
    PM_SAR_RANGE_THRES_REG |= lowLimit & PM_RANGE_LOW_MASK;
}


/*******************************************************************************
* Function Name: PM_SetHighLimit
********************************************************************************
*
* Summary:
*  Sets the low limit parameter for a limit condition.
*
* Parameters:
*  highLimit: The high limit for a limit condition.
*
* Return:
*  None.
*
*******************************************************************************/
void PM_SetHighLimit(uint32 highLimit)
{
    PM_SAR_RANGE_THRES_REG &= (uint32)(~PM_RANGE_HIGH_MASK);
    PM_SAR_RANGE_THRES_REG |= (uint32)(highLimit << PM_RANGE_HIGH_OFFSET);
}


/*******************************************************************************
* Function Name: PM_SetLimitMask
********************************************************************************
*
* Summary:
*  Sets the channel limit condition mask.
*
* Parameters:
*  mask: Sets which channels that may cause a
*  limit condition interrupt. Setting bits for channels that do not exist
*  will have no effect. For example, if only 6 channels were enabled,
*  setting a mask of 0x0103 would only enable the last two channels (0 and 1).
*
* Return:
*  None.
*
*******************************************************************************/
void PM_SetLimitMask(uint32 mask)
{
    PM_SAR_RANGE_INTR_MASK_REG = mask & PM_MAX_CHANNELS_EN_MASK;
}


/*******************************************************************************
* Function Name: PM_SetSatMask
********************************************************************************
*
* Summary:
*  Sets the channel saturation event mask.
*
* Parameters:
*  mask: Sets which channels that may cause a
*  saturation event interrupt. Setting bits for channels that do not exist
*  will have no effect. For example, if only 8 channels were enabled,
*  setting a mask of 0x01C0 would only enable two channels (6 and 7).
*
* Return:
*  None.
*
*******************************************************************************/
void PM_SetSatMask(uint32 mask)
{
    PM_SAR_SATURATE_INTR_MASK_REG = mask & PM_MAX_CHANNELS_EN_MASK;
}


/*******************************************************************************
* Function Name: PM_SetOffset
********************************************************************************
*
* Summary:
*   Description: Sets the ADC offset which is used by the functions
*   ADC_CountsTo_uVolts, ADC_CountsTo_mVolts and ADC_CountsTo_Volts
*   to substract the offset from the given reading
*   before calculating the voltage conversion.
*
* Parameters:
*  chan: ADC channel number.
*  offset: This value is a measured value when the
*          inputs are shorted or connected to the same input voltage.
*
* Return:
*  None.
*
* Global variables:
*  PM_Offset:  Modified to set the user provided offset.
*
*******************************************************************************/
void PM_SetOffset(uint32 chan, int16 offset)
{
    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < PM_TOTAL_CHANNELS_NUM);

    PM_offset[chan] = offset;
}


/*******************************************************************************
* Function Name: PM_SetGain
********************************************************************************
*
* Summary:
*  Description: Sets the ADC gain in counts per 10 volt for the voltage
*  conversion functions below. This value is set by default by the
*  reference and input range settings. It should only be used to further
*  calibrate the ADC with a known input or if an external reference is
*  used. Affects the ADC_CountsTo_uVolts, ADC_CountsTo_mVolts
*  and ADC_CountsTo_Volts functions by supplying the correct
*  conversion between ADC counts and voltage.
*
* Parameters:
*  chan: ADC channel number.
*  adcGain: ADC gain in counts per 10 volts.
*
* Return:
*  None.
*
* Global variables:
*  PM_CountsPer10Volt:  modified to set the ADC gain in counts
*   per 10 volt.
*
*******************************************************************************/
void PM_SetGain(uint32 chan, int32 adcGain)
{
    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < PM_TOTAL_CHANNELS_NUM);

    PM_countsPer10Volt[chan] = adcGain;
}


#if(PM_DEFAULT_JUSTIFICATION_SEL == PM__RIGHT)


    /*******************************************************************************
    * Function Name: PM_CountsTo_mVolts
    ********************************************************************************
    *
    * Summary:
    *  This function converts ADC counts to mVolts
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  adcCounts: Result from the ADC conversion
    *
    * Return:
    *  Results in mVolts
    *
    * Global variables:
    *  PM_countsPer10Volt:  used to convert ADC counts to mVolts.
    *  PM_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    *******************************************************************************/
    int16 PM_CountsTo_mVolts(uint32 chan, int16 adcCounts)
    {
        int16 mVolts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < PM_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(PM_DEFAULT_AVG_MODE == PM__ACCUMULATE)
            if((PM_channelsConfig[chan] & PM_AVERAGING_EN) != 0u)
            {
                adcCounts /= PM_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* PM_DEFAULT_AVG_MODE == PM__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= PM_offset[chan];

        mVolts = (int16)((((int32)adcCounts * PM_10MV_COUNTS) + ( (adcCounts > 0) ?
                 (PM_countsPer10Volt[chan] / 2) : (-(PM_countsPer10Volt[chan] / 2)) ))
                 / PM_countsPer10Volt[chan]);

        return( mVolts );
    }


    /*******************************************************************************
    * Function Name: PM_CountsTo_uVolts
    ********************************************************************************
    *
    * Summary:
    *  This function converts ADC counts to micro Volts
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  adcCounts: Result from the ADC conversion
    *
    * Return:
    *  Results in uVolts
    *
    * Global variables:
    *  PM_countsPer10Volt:  used to convert ADC counts to uVolts.
    *  PM_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    * Theory:
    *  Care must be taken to not exceed the maximum value for a 31 bit signed
    *  number in the conversion to uVolts and at the same time not loose
    *  resolution.
    *  To convert adcCounts to microVolts it is required to be multiplied
    *  on 10 million and later divide on gain in counts per 10V.
    *
    *******************************************************************************/
    int32 PM_CountsTo_uVolts(uint32 chan, int16 adcCounts)
    {
        int64 uVolts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < PM_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(PM_DEFAULT_AVG_MODE == PM__ACCUMULATE)
            if((PM_channelsConfig[chan] & PM_AVERAGING_EN) != 0u)
            {
                adcCounts /= PM_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* PM_DEFAULT_AVG_MODE == PM__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= PM_offset[chan];

        uVolts = ((int64)adcCounts * PM_10UV_COUNTS) / PM_countsPer10Volt[chan];

        return( (int32)uVolts );
    }


    /*******************************************************************************
    * Function Name: PM_CountsTo_Volts
    ********************************************************************************
    *
    * Summary:
    *  Converts the ADC output to Volts as a floating point number.
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  Result from the ADC conversion
    *
    * Return:
    *  Results in Volts
    *
    * Global variables:
    *  PM_countsPer10Volt:  used to convert ADC counts to Volts.
    *  PM_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    *******************************************************************************/
    float32 PM_CountsTo_Volts(uint32 chan, int16 adcCounts)
    {
        float32 volts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < PM_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(PM_DEFAULT_AVG_MODE == PM__ACCUMULATE)
            if((PM_channelsConfig[chan] & PM_AVERAGING_EN) != 0u)
            {
                adcCounts /= PM_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* PM_DEFAULT_AVG_MODE == PM__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= PM_offset[chan];

        volts = ((float32)adcCounts * PM_10V_COUNTS) / (float32)PM_countsPer10Volt[chan];

        return( volts );
    }

#endif /* End PM_DEFAULT_JUSTIFICATION_SEL == PM__RIGHT */


/* [] END OF FILE */
